import React, { useState, useMemo, useCallback } from 'react';
import { X, Download, Sparkles, GripVertical, Check, Copy, Layers, Code, FileText, Palette as PaletteIcon } from 'lucide-react';
import { colord } from 'colord';

const PURPOSE_OPTIONS = [
    { id: 'landing', label: 'Landing Page', description: 'Hero sections, CTAs, marketing focus' },
    { id: 'saas', label: 'SaaS Dashboard', description: 'Data-dense, neutral backgrounds, clear hierarchy' },
    { id: 'ecommerce', label: 'E-commerce', description: 'Product focus, trust signals, action buttons' },
    { id: 'mobile', label: 'Mobile App', description: 'Touch targets, system colors, dark mode ready' },
    { id: 'blog', label: 'Blog / Portfolio', description: 'Reading comfort, typography focus, minimal accents' },
    { id: 'custom', label: 'Custom / Other', description: 'General-purpose design system' },
];

const ROLE_DEFINITIONS = [
    { id: 'primary', label: 'Primary Brand', description: 'Main brand color, logos, key elements' },
    { id: 'background', label: 'Background', description: 'Page/app background color' },
    { id: 'surface', label: 'Surface / Card', description: 'Cards, modals, elevated surfaces' },
    { id: 'text', label: 'Text', description: 'Primary body text color' },
    { id: 'accent', label: 'Accent / CTA', description: 'Calls-to-action, interactive highlights' },
];

const PaletteExportModal = ({ colors, onClose }) => {
    const [step, setStep] = useState(1); // 1: Purpose, 2: Assign Roles, 3: Preview & Export
    const [purpose, setPurpose] = useState(null);
    const [roleAssignments, setRoleAssignments] = useState({
        primary: colors[0] || '#6366f1',
        background: null,
        surface: null,
        text: null,
        accent: null,
    });
    const [draggedColor, setDraggedColor] = useState(null);
    const [copied, setCopied] = useState(false);

    // Auto-assign colors based on luminance
    const autoAssignRoles = useCallback(() => {
        const sorted = [...colors].sort((a, b) => colord(b).luminance() - colord(a).luminance());
        // Lightest for BG, next for surface, darkest for text, most saturated for accent
        const mostSaturated = [...colors].sort((a, b) => colord(b).toHsl().s - colord(a).toHsl().s)[0];

        setRoleAssignments({
            primary: colors[0],
            background: sorted[0], // Lightest
            surface: sorted[1] || sorted[0],
            text: sorted[sorted.length - 1], // Darkest
            accent: mostSaturated,
        });
    }, [colors]);

    const handleDragStart = (color) => {
        setDraggedColor(color);
    };

    const handleDrop = (roleId) => {
        if (draggedColor) {
            setRoleAssignments(prev => ({ ...prev, [roleId]: draggedColor }));
            setDraggedColor(null);
        }
    };

    const handleDragOver = (e) => {
        e.preventDefault();
    };

    // Generate the AI-ready document
    const generateDocument = useMemo(() => {
        const purposeLabel = PURPOSE_OPTIONS.find(p => p.id === purpose)?.label || 'General Purpose';
        const contrastBgText = roleAssignments.background && roleAssignments.text
            ? colord(roleAssignments.background).contrast(colord(roleAssignments.text)).toFixed(2)
            : 'N/A';
        const contrastBgAccent = roleAssignments.background && roleAssignments.accent
            ? colord(roleAssignments.background).contrast(colord(roleAssignments.accent)).toFixed(2)
            : 'N/A';

        return `# 🎨 Design System: ${purposeLabel}

Generated by Color Coder • ${new Date().toLocaleDateString()}

---

## Color Palette Roles

| Role | HEX | Usage |
|------|-----|-------|
| Primary Brand | \`${roleAssignments.primary || 'Not Set'}\` | Main brand color, logos, key elements |
| Background | \`${roleAssignments.background || 'Not Set'}\` | Page/app background |
| Surface | \`${roleAssignments.surface || 'Not Set'}\` | Cards, modals, elevated surfaces |
| Text | \`${roleAssignments.text || 'Not Set'}\` | Primary body text |
| Accent / CTA | \`${roleAssignments.accent || 'Not Set'}\` | Buttons, links, interactive highlights |

---

## CSS Custom Properties

\`\`\`css
:root {
  --color-primary: ${roleAssignments.primary || '#6366f1'};
  --color-background: ${roleAssignments.background || '#ffffff'};
  --color-surface: ${roleAssignments.surface || '#f8fafc'};
  --color-text: ${roleAssignments.text || '#1e293b'};
  --color-accent: ${roleAssignments.accent || '#6366f1'};
}
\`\`\`

---

## Tailwind CSS Configuration

\`\`\`javascript
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      colors: {
        primary: '${roleAssignments.primary || '#6366f1'}',
        background: '${roleAssignments.background || '#ffffff'}',
        surface: '${roleAssignments.surface || '#f8fafc'}',
        text: '${roleAssignments.text || '#1e293b'}',
        accent: '${roleAssignments.accent || '#6366f1'}',
      },
    },
  },
};
\`\`\`

---

## Accessibility Notes

- **Background ↔ Text Contrast**: ${contrastBgText}:1 ${parseFloat(contrastBgText) >= 4.5 ? '✅ WCAG AA Pass' : '⚠️ May not meet WCAG AA'}
- **Background ↔ Accent Contrast**: ${contrastBgAccent}:1 ${parseFloat(contrastBgAccent) >= 4.5 ? '✅ WCAG AA Pass' : '⚠️ Check for interactive elements'}

---

## Usage Guidelines (60-30-10 Rule)

1. **60% - Background/Neutral**: Use \`--color-background\` for the main canvas. This creates visual rest.
2. **30% - Surface/Secondary**: Use \`--color-surface\` for cards, sidebars, and secondary containers.
3. **10% - Accent/Primary**: Reserve \`--color-accent\` for CTAs and \`--color-primary\` for brand moments.

---

## AI Implementation Prompt

> "Implement this design system using the following color tokens. Use the **Background** color for the page base, **Surface** for cards and modals, **Text** for all readable content, **Primary** for brand elements like logos and headers, and **Accent** exclusively for call-to-action buttons and interactive highlights. Ensure all text on backgrounds meets WCAG AA contrast requirements (4.5:1 minimum)."

---

*Generated with ❤️ by Color Coder*
`;
    }, [roleAssignments, purpose]);

    const handleCopy = () => {
        navigator.clipboard.writeText(generateDocument);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownload = () => {
        const blob = new Blob([generateDocument], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `design-system-${purpose || 'palette'}-${Date.now()}.md`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-[100] p-4">
            <div className="bg-white w-full max-w-3xl max-h-[90vh] overflow-hidden rounded-2xl shadow-2xl flex flex-col">
                {/* Header */}
                <div className="flex items-center justify-between p-4 md:p-6 border-b bg-gradient-to-r from-indigo-600 to-purple-600 text-white">
                    <div className="flex items-center gap-3">
                        <div className="p-2 bg-white/20 rounded-xl">
                            <FileText className="w-5 h-5" />
                        </div>
                        <div>
                            <h2 className="text-lg md:text-xl font-black uppercase tracking-tight">Export for AI</h2>
                            <p className="text-xs text-white/70">Generate an AI-ready design system document</p>
                        </div>
                    </div>
                    <button onClick={onClose} className="p-2 hover:bg-white/20 rounded-full transition-colors">
                        <X className="w-5 h-5" />
                    </button>
                </div>

                {/* Progress Steps */}
                <div className="flex items-center justify-center gap-2 p-4 border-b bg-gray-50">
                    {[1, 2, 3].map(s => (
                        <React.Fragment key={s}>
                            <div className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-black transition-all ${step >= s ? 'bg-indigo-600 text-white' : 'bg-gray-200 text-gray-500'}`}>
                                {step > s ? <Check className="w-4 h-4" /> : s}
                            </div>
                            {s < 3 && <div className={`w-12 h-1 rounded-full transition-all ${step > s ? 'bg-indigo-600' : 'bg-gray-200'}`} />}
                        </React.Fragment>
                    ))}
                </div>

                {/* Content Area */}
                <div className="flex-1 overflow-y-auto p-4 md:p-6">
                    {/* Step 1: Purpose Selection */}
                    {step === 1 && (
                        <div className="space-y-4">
                            <h3 className="text-lg font-bold text-gray-900">What are you building?</h3>
                            <p className="text-sm text-gray-500">This helps us tailor the color role suggestions and the generated prompt.</p>
                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                                {PURPOSE_OPTIONS.map(opt => (
                                    <button
                                        key={opt.id}
                                        onClick={() => setPurpose(opt.id)}
                                        className={`p-4 rounded-xl border-2 text-left transition-all ${purpose === opt.id ? 'border-indigo-600 bg-indigo-50 ring-4 ring-indigo-100' : 'border-gray-200 hover:border-gray-300'}`}
                                    >
                                        <div className="font-bold text-gray-900">{opt.label}</div>
                                        <div className="text-xs text-gray-500 mt-1">{opt.description}</div>
                                    </button>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Step 2: Role Assignment */}
                    {step === 2 && (
                        <div className="space-y-6">
                            <div className="flex items-center justify-between">
                                <div>
                                    <h3 className="text-lg font-bold text-gray-900">Assign Color Roles</h3>
                                    <p className="text-sm text-gray-500">Drag colors to their semantic roles, or auto-assign.</p>
                                </div>
                                <button
                                    onClick={autoAssignRoles}
                                    className="flex items-center gap-2 px-4 py-2 bg-indigo-100 text-indigo-700 rounded-lg hover:bg-indigo-200 transition-colors text-sm font-bold"
                                >
                                    <Sparkles className="w-4 h-4" />
                                    Auto-Assign
                                </button>
                            </div>

                            {/* Palette Colors (Draggable) */}
                            <div className="p-4 bg-gray-50 rounded-xl border border-gray-100">
                                <div className="text-xs font-black uppercase text-gray-400 mb-3">Your Palette</div>
                                <div className="flex flex-wrap gap-3">
                                    {colors.map((color, i) => (
                                        <div
                                            key={i}
                                            draggable
                                            onDragStart={() => handleDragStart(color)}
                                            className="w-14 h-14 rounded-xl shadow-lg cursor-grab active:cursor-grabbing border-4 border-white flex items-center justify-center transition-transform hover:scale-110"
                                            style={{ backgroundColor: color }}
                                        >
                                            <GripVertical className="w-4 h-4 text-white/50" />
                                        </div>
                                    ))}
                                </div>
                            </div>

                            {/* Role Slots (Droppable) */}
                            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                                {ROLE_DEFINITIONS.map(role => (
                                    <div
                                        key={role.id}
                                        onDragOver={handleDragOver}
                                        onDrop={() => handleDrop(role.id)}
                                        className={`p-4 rounded-xl border-2 border-dashed transition-all ${roleAssignments[role.id] ? 'border-indigo-300 bg-indigo-50' : 'border-gray-200 bg-gray-50 hover:border-gray-300'}`}
                                    >
                                        <div className="flex items-center justify-between mb-2">
                                            <span className="text-xs font-black uppercase text-gray-500">{role.label}</span>
                                            {roleAssignments[role.id] && (
                                                <div className="w-6 h-6 rounded-full border-2 border-white shadow-md" style={{ backgroundColor: roleAssignments[role.id] }} />
                                            )}
                                        </div>
                                        <p className="text-[10px] text-gray-400">{role.description}</p>
                                        {roleAssignments[role.id] && (
                                            <div className="mt-2 text-xs font-mono text-gray-600 bg-white px-2 py-1 rounded">{roleAssignments[role.id]}</div>
                                        )}
                                    </div>
                                ))}
                            </div>

                            {/* Live Mini Preview */}
                            <div className="p-4 rounded-xl border border-gray-200 space-y-3" style={{ backgroundColor: roleAssignments.background || '#f8fafc' }}>
                                <div className="text-xs font-black uppercase" style={{ color: roleAssignments.text || '#1e293b' }}>Live Preview</div>
                                <div className="p-4 rounded-lg shadow-md" style={{ backgroundColor: roleAssignments.surface || '#ffffff' }}>
                                    <div className="font-bold text-lg mb-1" style={{ color: roleAssignments.primary || '#6366f1' }}>Card Title</div>
                                    <p className="text-sm mb-3" style={{ color: roleAssignments.text || '#1e293b' }}>This is example body text on a card surface.</p>
                                    <button className="px-4 py-2 rounded-lg text-white text-sm font-bold" style={{ backgroundColor: roleAssignments.accent || '#6366f1' }}>
                                        Call to Action
                                    </button>
                                </div>
                            </div>
                        </div>
                    )}

                    {/* Step 3: Preview & Export */}
                    {step === 3 && (
                        <div className="space-y-4">
                            <div className="flex items-center justify-between">
                                <h3 className="text-lg font-bold text-gray-900">Your AI-Ready Document</h3>
                                <div className="flex gap-2">
                                    <button onClick={handleCopy} className="flex items-center gap-2 px-3 py-1.5 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors text-sm font-bold">
                                        {copied ? <Check className="w-4 h-4 text-green-600" /> : <Copy className="w-4 h-4" />}
                                        {copied ? 'Copied!' : 'Copy'}
                                    </button>
                                    <button onClick={handleDownload} className="flex items-center gap-2 px-3 py-1.5 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors text-sm font-bold">
                                        <Download className="w-4 h-4" />
                                        Download .md
                                    </button>
                                </div>
                            </div>
                            <div className="p-4 bg-gray-900 text-gray-100 rounded-xl overflow-x-auto max-h-[50vh] overflow-y-auto">
                                <pre className="text-xs font-mono whitespace-pre-wrap">{generateDocument}</pre>
                            </div>
                        </div>
                    )}
                </div>

                {/* Footer Navigation */}
                <div className="flex items-center justify-between p-4 border-t bg-gray-50">
                    <button
                        onClick={() => setStep(s => Math.max(1, s - 1))}
                        disabled={step === 1}
                        className="px-4 py-2 text-gray-600 hover:bg-gray-200 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed font-bold text-sm"
                    >
                        Back
                    </button>
                    {step < 3 ? (
                        <button
                            onClick={() => setStep(s => Math.min(3, s + 1))}
                            disabled={step === 1 && !purpose}
                            className="px-6 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed font-bold text-sm"
                        >
                            Continue
                        </button>
                    ) : (
                        <button onClick={onClose} className="px-6 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors font-bold text-sm">
                            Done
                        </button>
                    )}
                </div>
            </div>
        </div>
    );
};

export default PaletteExportModal;
